# Generated by Django 4.2.16 on 2024-10-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.orcamento')),
                ('produto_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.produtoservico')),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='produtos_servicos',
            field=models.ManyToManyField(through='orcamentos.OrcamentoItem', to='orcamentos.produtoservico'),
        ),
    ]
